### PR TITLE
Fixed the text overflow issue in small devices

### PR DESCRIPTION
**Pull request by rishav-jha-mech**
# Fixed the text overflow issue in small devices.

Now the website is completely responsive !

### CODE REVIEW

**Comment by jdeniau** [comment]
Hi @rishav-jha-mech 

If I apply your change, I got the following great content

image

😬 

Can you tell me more about what you are trying to fix here ?

Thanks

**Comment by rishav-jha-mech** [comment]
Im sorry 😥 actually i didn't go through the whole website i just saw the problem with the landing page.

## **Earlier in smaller devices (device width< 425px) the website would look like**


Documentation latest@main — Immutable js - Google Chrome 22-11-2021 08_25_41

## **And after the fix it looks like**


Documentation latest@main — Immutable js - Google Chrome 22-11-2021 08_26_14


### The docs page was already responsive, but because of my first commit docs page got messed up (i did not see that page), however that is completely fixed in the latest commit and now the docs page looks like this.

Documentation latest@main — Immutable js - Google Chrome 22-11-2021 08_23_14

**Comment by jdeniau** [comment]
OK great! I focused on the doc page only without testing the home page.
Thank you for your PR!

**Comment by jdeniau** [comment]
Thanks @rishav-jha-mech

**Pull request merged**
