### PR TITLE
Add partition to flow spec

### PR DESCRIPTION
**Pull request by Dagur**

### CODE REVIEW

**Comment by jdeniau** [comment]
> Cannot use type without exactly 1 type argument. [nonpolymorphic-type-app]

It seems that tuples are handled this way in flow:

```js
[this, this]
```

and not 

```
Array<this, this>
```

[source](https://flow.org/en/docs/types/tuples/)

Or it might be an issue with an old version of flow. If you want, you can upgrade the flow version to a most recent one

**Comment by Dagur** [comment]
Yeah this was completely wrong, I'm not sure why it wasn't flagged.
I'm fixing this now

**Comment by Dagur** [comment]
Should be alright now btw

**Comment by jdeniau** [comment]
Thanks @Dagur . Released in `4.2.2`

**Comment by Dagur** [comment]
Thank you too. 
One question though, the latest version on npm is still 4.2.1. Is that just them being slow?

**Comment by jdeniau** [comment]
@Dagur thanks for notifying me, the released process did fail. The `4.2.2` is now available on npmjs

**Comment by Dagur** [comment]
awesome. Thanks!

**Pull request merged**
