### PR TITLE
add 'Complementary Tools' section to website

### PR DESCRIPTION
**Pull request by eitanschreiber123**
add a new section to the website with a list of libraries and tools to use with immutable-js

### CODE REVIEW

**Comment by leebyron** [comment]
Thanks for working on this! Mind attaching some screenshots of the main page and the tools page both in desktop and mobile views?

**Comment by eitanschreiber123** [comment]
screen shot 2019-02-14 at 2 24 46 pm
screen shot 2019-02-14 at 2 24 54 pm
screen shot 2019-02-14 at 2 25 10 pm
screen shot 2019-02-14 at 2 25 17 pm
screen shot 2019-02-14 at 2 26 46 pm
screen shot 2019-02-14 at 2 26 53 pm
screen shot 2019-02-14 at 2 26 59 pm
screen shot 2019-02-14 at 2 27 03 pm
screen shot 2019-02-14 at 2 25 51 pm
screen shot 2019-02-14 at 2 25 54 pm
screen shot 2019-02-14 at 2 26 01 pm
screen shot 2019-02-14 at 2 26 04 pm
screen shot 2019-02-14 at 2 26 10 pm
screen shot 2019-02-14 at 2 26 14 pm
screen shot 2019-02-14 at 2 26 22 pm
screen shot 2019-02-14 at 2 26 26 pm
screen shot 2019-02-14 at 2 25 24 pm
screen shot 2019-02-14 at 2 25 28 pm
screen shot 2019-02-14 at 2 25 38 pm
screen shot 2019-02-14 at 2 25 42 pm

**Comment by leebyron** [comment]
Thanks for that!

It looks like the display of the links in the header are broken by this change compared to the current site. You can see the links in your screenshots are wrapping across multiple lines and spread the width of the page where they should be tightly aligned to the right side of content on the desktop view and should fit within one line on the mobile view.

I think the root issue is that your change affected the media query for the header

**Comment by eitanschreiber123** [comment]
i'll fix it on desktop but i don't think there's enough room for the links to fit on one line on mobile and have enough space between them

**Comment by eitanschreiber123** [comment]
i fixed it 

screen shot 2019-02-15 at 9 33 23 am
screen shot 2019-02-15 at 9 33 30 am
screen shot 2019-02-15 at 9 33 43 am
screen shot 2019-02-15 at 9 33 50 am
screen shot 2019-02-15 at 9 33 59 am
screen shot 2019-02-15 at 9 34 06 am
screen shot 2019-02-15 at 9 34 13 am
screen shot 2019-02-15 at 9 34 20 am
screen shot 2019-02-15 at 9 34 30 am
screen shot 2019-02-15 at 9 34 36 am
screen shot 2019-02-15 at 9 34 48 am
screen shot 2019-02-15 at 9 34 56 am
screen shot 2019-02-15 at 9 35 03 am
screen shot 2019-02-15 at 9 35 09 am
screen shot 2019-02-15 at 9 35 18 am
screen shot 2019-02-15 at 9 35 24 am
screen shot 2019-02-15 at 9 35 33 am
screen shot 2019-02-15 at 9 35 40 am
screen shot 2019-02-15 at 9 35 49 am
screen shot 2019-02-15 at 9 35 59 am

**Pull request closed without merging**
